### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by artalar** [lukeed/tsm#24]
Any plans for watch mode?

**Comment by lukeed** [comment]
No, not sure how that makes any sense for the usage. mind sharing an example? tsm is basically a `node` replacement or used within existing programs as a transformer

**Comment by leosuncin** [comment]
> No, not sure how that makes any sense for the usage. mind sharing an example? tsm is basically a `node` replacement or used within existing programs as a transformer

As a replace of `nodemon` or `ts-node-dev`

**Comment by TrySound** [comment]
We implement watch mode like this. The use case is restarting server on any change. Very handy.

```js
import { spawn } from 'child_process';
import { watch } from 'watchlist';

let childProcess = null;

const startServer = () => {
  if (childProcess) {
    childProcess.kill();
  }

  console.info('Starting/Restarting dev server');

  childProcess = spawn('node', ['--loader=tsm', 'src/docs.ts'], {
    stdio: 'inherit',
    env: process.env,
  });
};

watch(['.'], startServer, { eager: true });
```

**Comment by pma9** [comment]
You can use nodemon with config files that use tsm. https://github.com/remy/nodemon#config-files

**Comment by JanTvrdik** [comment]
Or [tsx watch](https://github.com/esbuild-kit/tsx#watch-mode).
