### ISSUE TITLE
[Feature]: support dynamic import by default

### ISSUE THREAD

**Issue by hardfist** [lukeed/tsm#27]
when I use tsm register  to transpile module which contains dynamic import, it's broken
* src/index.ts
```ts
async function main(){
  const mod = await import('./lib');
}
main();
```
* src/lib.ts
```ts
export const answer = 42;
```
It's broken
![image](https://user-images.githubusercontent.com/8898718/147609558-ffaa7150-fe99-4fb9-b049-2a7ca343f3dc.png)

It's because esbuild will keep dynamic import for high version of node, even you set format=cjs https://github.com/evanw/esbuild/issues/1636
![image](https://user-images.githubusercontent.com/8898718/147609697-92cd6beb-c8b3-4cc8-86f1-24399f249cd4.png)

when I set target to node12, it works fine now, because it will transform dynamic import to require
* tsm.js
```
module.exports = {
  common: {
   target: 'node12'
  }
}
```
so I think we could set target=node12 by default to support dynamic import by default

**Comment by lukeed** [comment]
What versions of Node and esbuild are you using? The support range for import() was fixed here: https://github.com/evanw/esbuild/issues/1772

It's not wise to make node12 the target for all runtimes, because it's untrue for non-12.x runtimes.

**Comment by hardfist** [comment]
I'm using node@16.8.0
