### ISSUE TITLE
Deprecated hooks

### ISSUE THREAD

**Issue by kran6a** [lukeed/tsm#34]
On the lastest node.js version the following error is thrown:

`DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource`

Meaning some features will not work properly unless those hooks are moved into the new `load` hook.

**Comment by TrySound** [comment]
Not an error. Just a warning. This is because older versions are still supported along with new hooks. Shouldn't affect anything.

**Comment by lukeed** [comment]
Closing as duplicate of #12
