### ISSUE TITLE
Transformation does not support plugins; Not working for Relay

### ISSUE THREAD

**Issue by theKashey** [lukeed/tsm#35]
👋 thanks for amazing tool. Being using it for quite a while and everything was fine... until today :(

```
Invariant Violation: graphql: Unexpected invocation at runtime. 
Either the Babel transform was not set up, or it failed to identify this call site. 
Make sure it is being used verbatim as `graphql`. 
Note also that there cannot be a space between graphql and the backtick that follows.
..../node_modules/relay-runtime/lib/query/GraphQLTag.js:25:52
```

We have 3 different ways to run our code:
- via babel, where babel plugin does the job
- via esbuild, where we have another `plugin` doing required transformations
- via node/tms where... we cannot hook into transformation process and change a few bits and pieces unless we override `Module._compile` in the same way you do to apply required transformations.

----

In order to provide flexibility for the end solution I want to steer issue from "not supporting plugins"(`transformSync` just dont support it) to the _actual_ problem I am facing with graphql.

Similar problem might occur while using any library which heavy relies on babel transformation step, and might be not for all of them `tsm` should work (and it does not right now). 

But is there anything we can do?

**Comment by maraisr** [comment]
Hmmm — yeah relay's runtime does an immediate throw coz it relies on transformations. SWC does this trough a [built-in transform](https://github.com/vercel/next.js/blob/fdfa3c7baef221e637edd76c8b13aa1950d26a1f/packages/next-swc/crates/core/src/relay.rs).

with esbuild [there exists a plugin](https://gist.github.com/sciyoshi/34e5865f2523848f0d60b4cdd49382ee) which you can put in your `tsm.config.js` file which is ready by this tool [through a configuration file](https://github.com/lukeed/tsm/blob/master/docs/configuration.md#config-file).

I do not believe tsm to have first-class support for relay, and in this case, please refer to the above.

**Comment by theKashey** [comment]
Unfortunately `tsm` configuration (and `esbuild.tranformSync`) does not support plugins or any other way to transform sources.

**Comment by lukeed** [comment]
esbuild only accepts plugins via its `build` method, which isn't used here as you've pointed out.
