### ISSUE TITLE
sharing: tsm succesfully chains with another --loader

### ISSUE THREAD

**Issue by iambumblehead** [lukeed/tsm#38]
The tsm and esmock loaders can be chained together. This example, uses them with node 18s new test runner to run a passing test,
```console
node --loader=tsm --loader=esmock --test *ts
```

[this PR adds a tsm unit-test][0] to esmock

[0]: https://github.com/iambumblehead/esmock/pull/81

**Comment by lukeed** [comment]
Correct, Node versions `16.17.0` and `18.6.0` allow more than one `--loader` to be used; see [history notes here](https://nodejs.org/api/esm.html#hooks)

Thanks for sharing~!
