### ISSUE TITLE
Support TypeScript 4.9 `satisfies` operator

### ISSUE THREAD

**Issue by karlhorky** [lukeed/tsm#42]
Hi @lukeed 👋 Hope you are well.

It would be great to be able to use [the TypeScript 4.9 `satisfies` operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#satisfies)!

However, currently, `tsm` throws an error when using `satisfies`:

```ts
import {AType} from '../a';

const a = 'abc' satisfies AType; // 💥 Expected ";" but found "satisfies"
```

Full error:

```
Error: R] Expected ";" but found "satisfies"

    /home/runner/work/courses/courses/packages/database/scripts/databaseFixtures/courseModules.ts:879:11:
      879 │ ] as const satisfies readonly CourseModule[];
          │            ~~~~~~~~~
          ╵            ;

/home/runner/work/courses/courses/node_modules/tsm/node_modules/esbuild/lib/main.js:1605
  let error = new Error(`${text}${summary}`);
              ^
```

This is supported in [`esbuild@^0.15.13`](https://github.com/evanw/esbuild/blob/478062d5310b27f1a6a259602a79bf84e233cc1d/CHANGELOG.md#01513)

---

### Workaround

Use Yarn/pnpm Resolutions (or npm Overrides) to force the version in `package.json`:

```json
{
  "resolutions": {
    "**/tsm/esbuild": "0.15.14"
  }
}
```

**Comment by karlhorky** [comment]
Thanks for 2d406efd5c1adceb4cc4894937ce61e3897c6165 @lukeed ! Will this be released in `tsm@2.2.3`?

**Comment by lukeed** [comment]
2.3.0 by eod

**Comment by karlhorky** [comment]
Nice, `tsm@2.3.0` is working, thanks! 🙌
